@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start
#AntiqueWhite:Пользователь реагирует на приложение;
if (Движение курсора) then (да)
#Business:Выбрать заливку;
#Business:Навести курсор на холст;
else (нет)
endif
    if (Нажата кнопка) then (нет)
    #Business:Курсор находится в движении;
    kill
    else (да)
        if (Кнопка отпущена) then (нет)
        #Business:Курсор находится в движении;
        kill
        else (да)
            if (Объект поменял цвет) then (да)
                else (нет)
                #Business:Цвет поменял холст;
               
endif
stop
@enduml
