@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start
#AntiqueWhite:Пользователь реагирует на приложение;
if (Движение курсора) then (да)
#Business:Выбрать инструмент;
#Business:Навести курсор на холст;
else (нет)
endif
    if (Нажата кнопка) then (нет)
    #Business:Курсор находится в движении;
    kill
    else (да)
    #Business:Двинуть мышь;
        if (Есть линия?) then (нет)
        #Business:Выбрана не кисть;
        kill

        else (да)

        if (Кнопка отпущена) then (да)
        #Business:Линия остановилась;
        else (нет)
        #Business:Продолжить рисовать линию;

endif
stop
@enduml
