@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start

#AntiqueWhite:Нажать на иконку кисти или ластика;
if (Нажата иконка кисти?) then (да)
else (нет)
#Cornsilk:Нажата иконка ластика;
endif
#AntiqueWhite:Нажать левой кнопкой мыши на холст;
#AntiqueWhite:Двигать мышкой на хосте;
if (Появилась линия черного цвета) then (да)
#Cornsilk:Была выбрана кисть;
else (нет)
#Cornsilk:Был выбран ластик,
для рисования необходимо выбрать кисть;
endif
#AntiqueWhite:Отпустить кнопку мыши;
#AntiqueWhite:Линия на холсте;
stop
@enduml
