@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start
#AntiqueWhite:Пользователь реагирует на приложение;
if (Движение курсора) then (да)
#Business:Выбрать фигуру;
#Business:Навести курсор на холст;
else (нет)
endif
    if (Нажата кнопка) then (нет)
    #Business:Ничего не присходит;
    kill
    else (да)
    #Business:Двинуть мышь, придавая нужную форму фигуре;
        if (Есть фигура?) then (нет)
        #Business:Выбрана не фигура;
        kill

        else (да)

        if (Кнопка отпущена) then (да)
        #Business:Фигура приняла статическое положение;
        else (нет)
        #Business:Продолжить двигать мышью, меняя форму фигуры;

endif
stop
@enduml
