@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start

#AntiqueWhite:Нажать на кнопку P;
#AntiqueWhite:Нажать на иконку палитры рядом с надписью;
#AntiqueWhite:Выбрать цвет;
#AntiqueWhite:Нажать "OK";
#AntiqueWhite:Поставить галочку напротив надписи;
#AntiqueWhite:Нажать "OK";
#AntiqueWhite:Выбрать и нарисовать фигуру;
if (Внутренний цвет фигуры - выбранный цвет?) then (да)
#Cornsilk:Галочка поставлена напротив надписи "Основной цвет";
else (нет)
if (Цвет линии фигуры поменял цвет?) then (да)
#Cornsilk:Галочка поставлена напротив надписи "Цвет обводки";
else (нет)
#Cornsilk:Галочка ни где не поставлена;
#Cornsilk:Необходимо поставить галочку, чтобы фигура поменяла цвет;
endif
endif
#AntiqueWhite:Фигура определенного цвета на холсте;
stop
@enduml
