@startuml
skinparam activity {
    DiamondBackgroundColor LightBlue
}
start

#AntiqueWhite:Нажать на иконку фигуры;
if (Зажата левая клавиша мыши на холсте?) then (да)
else (нет)
#Cornsilk:Зажать левую клавишу миши на холсте;
endif
#AntiqueWhite:Двинуть мышь в одно из направлений;
if (Кнопка мыши не зажата?) then (да)
else (нет)
#Cornsilk:Отпустить кнопку миши;
endif
#AntiqueWhite:Фигура приняла статическое положение на холсте;
stop
@enduml
