@startuml

skinparam actor {
    BackgroundColor OrangeRed/Orange
    BorderColor Orange
}


skinparam usecase {
    BackgroundColor Snow
    BorderColor Black    
}


left to right direction

actor User as User

rectangle "App"#AliceBlue/LightBlue {
    usecase "Использование Кисти" as br
    usecase "Использование Ластика" as er
    usecase "Использование Фигуры" as f
    usecase "Использование Заливки" as z
    usecase "Сохранение файла" as save
    usecase "Открытие файла" as open
    usecase "Отмена действия" as undo
    usecase "Выбор цвета" as col
    usecase "Рисование" as draw
    User --> br
    User --> er
    User --> f
    User --> z
    User --> save
    User --> open
    User --> undo
    User --> col
    br .. draw
    col .. br
    col .. f
    col .. z
    er .. draw
    z .. draw
    f .. draw
    
}

@enduml
