@startuml
state "Нажать на иконку заливки" as F
state "Навести курсор на холст" as Move
state "Нажать на кнопку" as Press
state "Объект залился цветом" as O
state "Холст залился цветом" as Can
state "Ожидание выбора инструмента" as W
state "Произошла заливка" as Stop
[*] --> W
W --> F
F : Выбрана заливка
F --> Move
Move : Курсор находится в движении
Move --> Press
Press : В момент нажатия курсор принимает статическое положение
Press --> O : Курсор на объекте
Press --> Can : Курсор на холсте
O --> Stop
Can --> Stop
Stop --> [*]

@enduml
